name = "gRPCClient"
uuid = "aaca4a50-36af-4a1d-b878-4c443f2061ad"
authors = ["Carroll Vance <cs.vance@icloud.com>"]
version = "1.0.0"

[deps]
FileWatching = "7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee"
LibCURL = "b27032c2-a3e7-50c8-80cd-2d36dbcbfd21"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
ProtoBuf = "3349acd9-ac6a-5e09-bcdb-63829b23a429"

[compat]
julia = "1.10"
FileWatching = "^1.10"
LibCURL = "~0.6.4"
PrecompileTools = "^1.2"
ProtoBuf = "~1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]